Beginning trial 1 of 1
Gathering sys log on node001
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/reinforcement/minigo/ml_perf/mlperf_log_utils.py", line 112, in mlperf_submission_log
    'cat /sys/module/mlx5_core/version'
  File "/opt/reinforcement/minigo/ml_perf/mlperf_log_utils.py", line 15, in query
    stderr=subprocess.DEVNULL
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'cat /sys/module/mlx5_core/version' returned non-zero exit status 1
ERR: Sys log gathering failed.
